// Translator for compositions management system
const translations = {
  compositions_management: {
    Français: "Gestion des Compositions",
    Anglais: "Compositions Management",
    Bambara: "Ɲɔngɔndanw Ɲɛnabɔli",
  },
  error_select_composition_number: {
    Français: "Veuillez sélectionner un numéro de composition.",
    Anglais: "Please select a composition number.",
    Bambara: "I ka kan ka ɲɔngɔndan nimoro dɔ sugandi.",
  },
  error_select_composition_date: {
    Français: "Veuillez sélectionner une date pour la composition.",
    Anglais: "Please select a date for the composition.",
    Bambara: "I ka kan ka ɲɔngɔndan don dɔ sugandi.",
  },
  error_select_one_class: {
    Français: "Veuillez sélectionner au moins une classe pour la composition.",
    Anglais: "Please select at least one class for the composition.",
    Bambara: "I ka kan ka kilasi kelen sugandi ɲɔngɔndan kama.",
  },
  error_composition_already_exists: {
    Français: "La composition {name} existe déjà pour cette année.",
    Anglais: "Composition {name} already exists for this year.",
    Bambara: "Ɲɔngɔndan {name} bɛ yen ka ban san in kɔnɔ.",
  },
  success_composition_updated: {
    Français: "La composition a été mise à jour avec succès!",
    Anglais: "The composition has been successfully updated!",
    Bambara: "Ɲɔngɔndan kɔnɔkow ladilanin don ni nɔɔrɔ ye!",
  },
  success_composition_created: {
    Français: "La composition a été créée avec succès!",
    Anglais: "The composition was successfully created!",
    Bambara: "Ɲɔngɔndan kura dabɔra ni nɔɔrɔ ye!",
  },
  error_saving_composition: {
    Français: "Erreur lors de la sauvegarde de la composition.",
    Anglais: "Error saving the composition.",
    Bambara: "Ɲɔngɔndan marali la, fili bɛ yen.",
  },
  error_delete_locked_composition: {
    Français:
      "Cette composition ne peut pas être supprimée car tous ses bulletins sont verrouillés.",
    Anglais:
      "This composition cannot be deleted because all its report cards are locked.",
    Bambara:
      "Nin ɲɔngɔndan tɛ se ka jɔsi, sabu a ka kalan-sɛbɛnw bɛɛ konkoronnen don.",
  },
  success_composition_deleted: {
    Français: "La composition a été supprimée avec succès!",
    Anglais: "The composition has been successfully deleted!",
    Bambara: "Ɲɔngɔndan jɔsira ni nɔɔrɔ ye!",
  },
  error_deleting_composition: {
    Français: "Erreur lors de la suppression de la composition.",
    Anglais: "Error deleting the composition.",
    Bambara: "Ɲɔngɔndan jɔsili la, fili bɛ yen.",
  },
  confirm_delete_title: {
    Français: "Confirmer la suppression",
    Anglais: "Confirm deletion",
    Bambara: "Jɔsili Yamaruyali",
  },
  confirm_delete_message: {
    Français: "Voulez-vous vraiment supprimer la composition",
    Anglais: "Do you really want to delete the composition",
    Bambara: "Yala i b'a fɛ ka ɲɔngɔndan nin jɔsi tiɲɛ na?",
  },
  of_date: {
    Français: "du",
    Anglais: "of",
    Bambara: "ka",
  },
  list_of_compositions: {
    Français: "Liste des Compositions",
    Anglais: "List of Compositions",
    Bambara: "Ɲɔngɔndanw ka jɛnsɛn",
  },
  sort_by: {
    Français: "Trier par :",
    Anglais: "Sort by:",
    Bambara: "A woloma ni :",
  },
  date_desc: {
    Français: "Date (récent → ancien)",
    Anglais: "Date (newest → oldest)",
    Bambara: "Don (kura → kɔrɔ)",
  },
  date_asc: {
    Français: "Date (ancien → récent)",
    Anglais: "Date (oldest → newest)",
    Bambara: "Don (kɔrɔ → kura)",
  },
  name_asc: {
    Français: "Numéro (croissant)",
    Anglais: "Number (ascending)",
    Bambara: "Nimoro (dɔgɔmani → kumaba)",
  },
  name_desc: {
    Français: "Numéro (décroissant)",
    Anglais: "Number (descending)",
    Bambara: "Nimoro (kumaba → dɔgɔmani)",
  },
  created_at_desc: {
    Français: "Créé (récent → ancien)",
    Anglais: "Created (newest → oldest)",
    Bambara: "Dilan don (kura → kɔrɔ)",
  },
  created_at_asc: {
    Français: "Créé (ancien → récent)",
    Anglais: "Created (oldest → newest)",
    Bambara: "Dilan don (kɔrɔ → kura)",
  },
  new_composition: {
    Français: "Nouvelle Composition",
    Anglais: "New Composition",
    Bambara: "Ɲɔngɔndan Kura",
  },
  no_composition_recorded: {
    Français: "Aucune composition enregistrée",
    Anglais: "No composition recorded",
    Bambara: "Ɲɔngɔndan si ma maralen tɛ",
  },
  click_new_composition_to_start: {
    Français: 'Cliquez sur "Nouvelle Composition" pour commencer',
    Anglais: 'Click on "New Composition" to start',
    Bambara: 'Digi "Ɲɔngɔndan kura" kan ka daminɛ',
  },
  name: {
    Français: "Nom",
    Anglais: "Name",
    Bambara: "Tɔgɔ",
  },
  date: {
    Français: "Date",
    Anglais: "Date",
    Bambara: "Don",
  },
  classes: {
    Français: "Classes",
    Anglais: "Classes",
    Bambara: "Kilasiw",
  },
  actions: {
    Français: "Actions",
    Anglais: "Actions",
    Bambara: "Kɛwalew",
  },
  locked: {
    Français: "Verrouillé",
    Anglais: "Locked",
    Bambara: "Datugulen",
  },
  edit: {
    Français: "Modifier",
    Anglais: "Edit",
    Bambara: "Yɛlɛma",
  },
  delete: {
    Français: "Supprimer",
    Anglais: "Delete",
    Bambara: "A jɔsi",
  },
  edit_composition: {
    Français: "Modifier la composition",
    Anglais: "Edit composition",
    Bambara: "Ɲɔngɔndan yɛlɛma",
  },
  composition_number: {
    Français: "Numéro de composition",
    Anglais: "Composition number",
    Bambara: "Ɲɔngɔndan nimoro",
  },
  composition_date: {
    Français: "Date de la composition",
    Anglais: "Composition date",
    Bambara: "Ɲɔngɔndan don",
  },
  concerned_classes: {
    Français: "Classes concernées",
    Anglais: "Concerned classes",
    Bambara: "Kilasiw minnu kɔnɔ",
  },
  locked_bulletin_tooltip: {
    Français: "Bulletin verrouillé - impossible de retirer cette classe",
    Anglais: "Locked bulletin - cannot remove this class",
    Bambara: "Kalan-sɛbɛn konkoronnen - nin kilasi tɛ se ka bɔ a la",
  },
  no_classes_available: {
    Français: "Aucune classe disponible. Veuillez d'abord créer des classes.",
    Anglais: "No classes available. Please create classes first.",
    Bambara: "Kilasi si tɛ sɔrɔ. Kilasiw dabɔ fɔlɔ.",
  },
  update_composition: {
    Français: "Mettre à jour la composition",
    Anglais: "Update composition",
    Bambara: "Ɲɔngɔndan kɔnɔkow ladilan",
  },
  create_composition: {
    Français: "Créer la composition",
    Anglais: "Create composition",
    Bambara: "Ɲɔngɔndan dabɔ",
  },
  close: {
    Français: "Fermer",
    Anglais: "Close",
    Bambara: "A datugu",
  },
  composition_options: {
    Français: [
      { value: "1", helper: "comp", label: "1ère Composition" },
      { value: "2", helper: "comp", label: "2ème Composition" },
      { value: "3", helper: "comp", label: "3ème Composition" },
      { value: "4", helper: "comp", label: "4ème Composition" },
      { value: "5", helper: "comp", label: "5ème Composition" },
      { value: "6", helper: "comp", label: "6ème Composition" },
      { value: "7", helper: "comp", label: "7ème Composition" },
      { value: "8", helper: "comp", label: "8ème Composition" },
      { value: "9", helper: "comp", label: "9ème Composition" },
      { value: "10", helper: "Trim", label: "1er Trimestre" },
      { value: "11", helper: "Trim", label: "2ème Trimestre" },
      { value: "12", helper: "Trim", label: "3ème Trimestre" },
      { value: "13", helper: "Seme", label: "1er Semestre" },
      { value: "14", helper: "Seme", label: "2ème Semestre" },
      { value: "15", helper: "Seme", label: "3ème Semestre" },
      { value: "16", helper: "Seme", label: "4ème Semestre" },
      { value: "17", helper: "Seme", label: "5ème Semestre" },
      { value: "18", helper: "Seme", label: "6ème Semestre" },
      { value: "19", helper: "Trim", label: "Mini Trimestre" },
      { value: "20", helper: "Def", label: "DEF Blanc" },
      { value: "21", helper: "Bac", label: "BAC Blanc" },
    ],
    Anglais: [
      { value: "1", helper: "comp", label: "1st Composition" },
      { value: "2", helper: "comp", label: "2nd Composition" },
      { value: "3", helper: "comp", label: "3rd Composition" },
      { value: "4", helper: "comp", label: "4th Composition" },
      { value: "5", helper: "comp", label: "5th Composition" },
      { value: "6", helper: "comp", label: "6th Composition" },
      { value: "7", helper: "comp", label: "7th Composition" },
      { value: "8", helper: "comp", label: "8th Composition" },
      { value: "9", helper: "comp", label: "9th Composition" },
      { value: "10", helper: "Trim", label: "1st Term" },
      { value: "11", helper: "Trim", label: "2nd Term" },
      { value: "12", helper: "Trim", label: "3rd Term" },
      { value: "13", helper: "Seme", label: "1st Semester" },
      { value: "14", helper: "Seme", label: "2nd Semester" },
      { value: "15", helper: "Seme", label: "3rd Semester" },
      { value: "16", helper: "Seme", label: "4th Semester" },
      { value: "17", helper: "Seme", label: "5th Semester" },
      { value: "18", helper: "Seme", label: "6th Semester" },
      { value: "19", helper: "Trim", label: "Mini Term" },
      { value: "20", helper: "Def", label: "Mock DEF" },
      { value: "21", helper: "Bac", label: "Mock BAC" },
    ],
    Bambara: [
      { value: "1", helper: "comp", label: "San Ɲɔngɔndan Fɔlɔ" },
      { value: "2", helper: "comp", label: "San Ɲɔngɔndan 2 nan" },
      { value: "3", helper: "comp", label: "San Ɲɔngɔndan 3 nan" },
      { value: "4", helper: "comp", label: "San Ɲɔngɔndan 4 nan" },
      { value: "5", helper: "comp", label: "San Ɲɔngɔndan 5 nan" },
      { value: "6", helper: "comp", label: "San Ɲɔngɔndan 6 nan" },
      { value: "7", helper: "comp", label: "San Ɲɔngɔndan 7 nan" },
      { value: "8", helper: "comp", label: "San Ɲɔngɔndan 8 nan" },
      { value: "9", helper: "comp", label: "San Ɲɔngɔndan 9 nan" },
      { value: "10", helper: "Trim", label: "Kalo Saba Ɲɔngɔndan Fɔlɔ" },
      { value: "11", helper: "Trim", label: "Kalo Saba Ɲɔngɔndan 2 nan" },
      { value: "12", helper: "Trim", label: "Kalo Saba Ɲɔngɔndan 3 nan" },
      { value: "13", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan Fɔlɔ" },
      { value: "14", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan 2 nan" },
      { value: "15", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan 3 nan" },
      { value: "16", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan 4 nan" },
      { value: "17", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan 5 nan" },
      { value: "18", helper: "Seme", label: "Kalo Wɔɔrɔ Ɲɔngɔndan 6 nan" },
      { value: "19", helper: "Trim", label: "Kalo Saba Ɲɔngɔndan fitini" },
      { value: "20", helper: "Def", label: "DEF labɛnni" },
      { value: "21", helper: "Bac", label: "BAC labɛnni" },
    ],
  },
};

export const translate = (key, language) => {
  return translations[key] ? translations[key][language] || key : key;
};
