const Translator = {
    Bambara: {
        welcome_text: "Ka aw ka kalanso ɲɛnabɔ k’a sɔrɔ aw tɛ fosin ɲɛdon Informatiki la !",
        create_db_text: "I KA DATABASE LABƐN",
        create_btn_text: "LABƐN",
        create_btn_text_2: "A LABƐN SISAN",
        select_color_text: "Kulɛri dɔ sugandi",
        create_input_info_text: "Aw ka kalanso tɔgɔ",
        error_empty: "⛔ Database tɔgɔ dili wajibiyalen don.",
        error_minLength: "⚠️ Tɔgɔ dɔgɔyalenba ka kan ka kɛ ni taamasiyɛn 3 ye.",
        error_maxLength: "⚠️ Tɔgɔ tɛ se ka tɛmɛ taamasiyɛn 45 kan.",
        error_invalidChars: "⚠️ Tɔgɔ in ka kan ka kɛ ni lɛtɛrɛw, nimɔrɔw, daɲɛw walima sɛbɛnnibolow dɔrɔn de ye.",
        creating_db_message: "Aw ka database labɛnni bɛ sen na...",
        loading_message: "Aw y'aw muɲu dɔɔni dɔrɔn, labɛn bɛ sen na...",
        loading_patient_message: "Aw ni cɛ aw ka muɲu na, labɛn tɔ man ca...",
        created_db_message: "Aw ka database labɛnni baara bantɔla filɛ ni ye...",
        color_text: "Kulɛriw",
        theme_text: "Tɛmu",
        add_new_text: "Farali",
        filter_text: "Wolomali",
        recherche_text: "ɲininin teliman...",
        classe_text: "Kilasiw",
        refresh_text: "Kurayali",
        all_text: "Bɛɛ",
        lang_name_text: "Kan",
        calculator_text: "Jatekɛla",
        calendar_text: "Donfilɛla",
        error_calculate_text: "Filikɛra",
        profile_text: "Kalanden",
        fullname_text: "Tɔgɔ Bɛɛ Jɛlen",
        firstname_text: "Tɔgɔ",
        lastname_text: "Jamu",
        surname_text: "Tɔgɔ Wɛrɛ",
        sexe_text: "Cɛya ni Musoya",
        birth_text: "Wolo San",
        age_text: "Si Hakɛ",
        years_text: "san",
        father_text: "Facɛ",
        mother_text: "Bamuso",
        contact_text: "Welesira",
        added_time_text: "Faradon",
        updated_time_text: "Yɛlɛmadon",
        status_text: "Cogoya",
        actif_text: "A ben",
        actif_text: "A ten",
        classe_text: "Kalanso",
        option_text: "Fɛnwɛrɛw",
        update_student_text: "Yɛlɛmalikɛ",
        see_detail_student_text: "Ko tɔw filɛ",
        deactive_student_text: "Ni labɔ u la",
        active_student_text: "Ni la segin",
        delete_student_text: "Ni jɔsi ka bɔɲin",
        filter_by_classe_text: "Ni sodenw",
        filter_A_to_Z_text: "Ni A fo Z",
        filter_date_insc_text: "Ni farali don",
        students_number_text: "Kalandenw bɛɛ la jɛlen hakɛ",
        classe_number_text: "Kalansodenw bɛɛ la jɛlen hakɛ",
        no_student_in_data_text: "Kalanso tɛ i bolo fɔlɔ wa kalanden fana tɛ i ka database kɔnɔ.",
        no_student_in_data_text_2: "kalanden fosi tɛ i ka database kɔnɔ fɔlɔ.",
        create_classe_in_data_text_2: "Aw ye butɔni digi min bɛ duguma walasa ka kalandew ladon.",
        create_classe_in_data_text: "Aw ye butɔni digi min bɛ duguma walasa ka kalanso dɔ dabɔ.",
        create_classe_btn_text: "Kalanso dɔ dabɔ",
        create_students_btn_text: "Kalandew dɔw ladon sissan",
        setting_text: "Paramɛtiri",
        dashboard_text: "Tabulo",
        week_days_name_array: ["Kar", "Tɛn", "Tar", "Ara", "Ala", "Jum", "Sib"],
    },
    Français: {
        welcome_text: "Gérez votre établissement sans aucune compétence en informatique !",
        create_db_text: "CRÉER UNE BASE DE DONNÉES",
        create_btn_text: "CRÉER",
        create_btn_text_2: "CRÉER MAINTENANT",
        select_color_text: "Choisir une couleur",
        create_input_info_text: "Nom de votre établissement",
        error_empty: "⛔ Le nom de la base de données est requis.",
        error_minLength: "⚠️ Le nom doit contenir au moins 3 caractères.",
        error_maxLength: "⚠️ Le nom ne peut pas dépasser 45 caractères.",
        error_invalidChars: "⚠️ Le nom ne doit contenir que des lettres, chiffres, tirets ou underscores.",
        creating_db_message: "Création de votre base de données en cours...",
        loading_message: "Veuillez patienter, chargement en cours...",
        loading_patient_message: "Veuillez patienter un instant, s'il vous plaît...",
        created_db_message: "Finalisation de la création de votre base de données...",
        color_text: "Couleurs",
        theme_text: "Thème",
        add_new_text: "Ajout",
        filter_text: "Filtre",
        recherche_text: "Recherche en direct...",
        classe_text: "Classes",
        refresh_text: "Rafraîchir",
        all_text: "Toutes",
        lang_name_text: "Langue",
        calculator_text: "Calculatrice",
        calendar_text: "Calendrier",
        error_calculate_text: "Erreur",
        profile_text: "Profil",
        fullname_text: "Nom Complet",
        firstname_text: "Prénom",
        lastname_text: "Nom",
        surname_text: "Surnom",
        sexe_text: "Sexe",
        birth_text: "Date de Naissance",
        age_text: "Âge",
        years_text: "ans",
        father_text: "Père",
        mother_text: "Mère",
        contact_text: "Contact",
        added_time_text: "Date d'ajout",
        updated_time_text: "Date de modification",
        status_text: "Status",
        actif_text: "Actif",
        actif_text: "Actif",
        classe_text: "Classe",
        option_text: "Option",
        update_student_text: "Modifier",
        see_detail_student_text: "Voir plus",
        deactive_student_text: "Désactiver",
        active_student_text: "Activer",
        delete_student_text: "Supprimer",
        filter_by_classe_text: "Par classe",
        filter_A_to_Z_text: "De A à Z",
        filter_date_insc_text: "Par date d'inscription",
        students_number_text: "Le nombre total des élèves",
        classe_number_text: "Le nombre total des classes",
        no_student_in_data_text: "Vous n'avez aucune classe et aucun élève dans votre base de donnée.",
        no_student_in_data_text_2: "Vous n'avez aucun élève dans votre base de donnée.",
        create_classe_in_data_text_2: "Veuillez cliquer sur le bouton ci-dessous pour ajouter des élèves.",
        create_classe_in_data_text: "Veuillez cliquer sur le bouton ci-dessous pour créer une classe.",
        create_classe_btn_text: "Créer une classe",
        create_students_btn_text: "Ajouter des élèves maintenant",
        setting_text: "Paramètre",
        dashboard_text: "Tableau de bord",
        week_days_name_array: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    },
    Anglais: {
        welcome_text: "Manage your institution with no IT skills required!",
        create_db_text: "CREATE A DATABASE",
        create_btn_text: "CREATE",
        create_btn_text_2: "CREATE NOW",
        select_color_text: "Choose a color",
        create_input_info_text: "Name of your institution",
        error_empty: "⛔ Database name is required.",
        error_minLength: "⚠️ The name must be at least 3 characters long.",
        error_maxLength: "⚠️ The name cannot exceed 45 characters.",
        error_invalidChars: "⚠️ The name must only contain letters, numbers, hyphens, or underscores.",
        creating_db_message: "Creating your database...",
        loading_message: "Please wait, loading in progress...",
        loading_patient_message: "Please wait a moment, please...",
        created_db_message: "Finalizing the creation of your database...",
        color_text: "Colors",
        theme_text: "Theme",
        add_new_text: "Add",
        filter_text: "Filter",
        recherche_text: "Live search...",
        classe_text: "Classes",
        refresh_text: "Refresh",
        all_text: "All",
        lang_name_text: "Language",
        calculator_text: "Calculator",
        calendar_text: "Agenda",
        error_calculate_text: "Error",
        profile_text: "Profile",
        fullname_text: "Full Name",
        firstname_text: "First Name",
        lastname_text: "Last Name",
        surname_text: "Surname",
        sexe_text: "Sex",
        birth_text: "Birth Date",
        age_text: "Age",
        years_text: "old years",
        father_text: "Father",
        mother_text: "Mother",
        contact_text: "Contact",
        added_time_text: "Added At",
        updated_time_text: "Updated At",
        status_text: "Status",
        actif_text: "Actif",
        actif_text: "Deactif",
        classe_text: "Classe",
        option_text: "Option",
        update_student_text: "Update",
        see_detail_student_text: "See more",
        deactive_student_text: "Deactive",
        active_student_text: "Active",
        delete_student_text: "Delete",
        filter_by_classe_text: "By classe",
        filter_A_to_Z_text: "From A to Z",
        filter_date_insc_text: "By registration date",
        students_number_text: "Total number of students",
        classe_number_text: "Total number of classes",
        no_student_in_data_text: "You have no classes and no students in your database.",
        no_student_in_data_text_2: "You have no students in your database.",
        create_classe_in_data_text_2: "Please click the button below to add your students.",
        create_classe_in_data_text: "Please click the button below to create a class.",
        create_classe_btn_text: "Create a class",
        create_students_btn_text: "Add students now",
        setting_text: "Settings",
        dashboard_text: "Dashboard",
        week_days_name_array: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    },
};

export { Translator };
