const Translator = {
    Bambara: {
        welcome_text: "Sii i ma ka sigi kɛnɛya ka taa don kɛlɛ, ni lafiɛlɛ kɔrɔ la.",
        create_db_text: "FURU NÙBÈE",
        create_btn_text: "FURU",
        create_btn_text_2: "FURU BANA",
        select_color_text: "Se ka tuma",
        create_input_info_text: "Furu nùbèe ka lafiɛlɛ",
        error_empty: "⛔ A ka dugulen ko labɛn !",
        error_minLength: "⚠️ A ka dugulen ko bɛ taa kelen ni saba !",
        error_maxLength: "⚠️ A ka dugulen ko ka taa bɛ taa talan ni tɔɔrɔ !",
        error_invalidChars: "⚠️ A ka dugulen ko kɛ bɛ yeɲin, baara, ni bɔ-joona bɛɛ kɛ !",
        creating_db_message: "Bambara : Création de votre base de données en cours...",
        loading_message: "Bambara : Veuillez patienter, chargement en cours...",
        loading_patient_message: "Bambara : Veuillez patienter un instant, s'il vous plaît...",
        created_db_message: "Bambara : Finalisation de la création de votre base de données...",
        color_text: "Kulɛriw",
        theme_text: "Tɛmu",
        add_new_text: "Farali",
        filter_text: "Wolomali",
        recherche_text: "ɲininin teliman...",
        calsse_text: "Kilasiw",
        refresh_text: "Kurayali",
        all_text: "Bɛɛ",
        lang_name_text: "Kan",
    },
    Français: {
        welcome_text: "Gérez votre établissement sans aucune compétence en informatique !",
        create_db_text: "CRÉER UNE BASE DE DONNÉES",
        create_btn_text: "CRÉER",
        create_btn_text_2: "CRÉER MAINTENANT",
        select_color_text: "Choisir une couleur",
        create_input_info_text: "Nom de votre établissement",
        error_empty: "⛔ Le nom de la base de données est requis.",
        error_minLength: "⚠️ Le nom doit contenir au moins 3 caractères.",
        error_maxLength: "⚠️ Le nom ne peut pas dépasser 30 caractères.",
        error_invalidChars: "⚠️ Le nom ne doit contenir que des lettres, chiffres, tirets ou underscores.",
        creating_db_message: "Création de votre base de données en cours...",
        loading_message: "Veuillez patienter, chargement en cours...",
        loading_patient_message: "Veuillez patienter un instant, s'il vous plaît...",
        created_db_message: "Finalisation de la création de votre base de données...",
        color_text: "Couleurs",
        theme_text: "Thème",
        add_new_text: "Ajout",
        filter_text: "Filtre",
        recherche_text: "Recherche en direct...",
        calsse_text: "Classes",
        refresh_text: "Rafraîchir",
        all_text: "Toutes",
        lang_name_text: "Langue",
    },
    Anglais: {
        welcome_text: "Manage your institution with no IT skills required!",
        create_db_text: "CREATE A DATABASE",
        create_btn_text: "CREATE",
        create_btn_text_2: "CREATE NOW",
        select_color_text: "Choose a color",
        create_input_info_text: "Name of your institution",
        error_empty: "⛔ Database name is required.",
        error_minLength: "⚠️ The name must be at least 3 characters long.",
        error_maxLength: "⚠️ The name cannot exceed 30 characters.",
        error_invalidChars: "⚠️ The name must only contain letters, numbers, hyphens, or underscores.",
        creating_db_message: "Creating your database...",
        loading_message: "Please wait, loading in progress...",
        loading_patient_message: "Please wait a moment, please...",
        created_db_message: "Finalizing the creation of your database...",
        color_text: "Colors",
        theme_text: "Theme",
        add_new_text: "Add",
        filter_text: "Filter",
        recherche_text: "Live search...",
        calsse_text: "Classes",
        refresh_text: "Refresh",
        all_text: "All",
        lang_name_text: "Language",
    },
};

export { Translator };
