const Translator = {
    Bambara: {
        welcome_text: "Sii i ma ka sigi kɛnɛya ka taa don kɛlɛ, ni lafiɛlɛ kɔrɔ la.",
        create_db_text: "FURU NÙBÈE",
        create_btn_text: "FURU",
        create_btn_text_2: "FURU BANA",
        select_color_text: "Se ka tuma",
        create_input_info_text: "Furu nùbèe ka lafiɛlɛ",
        error_empty: "⛔ A ka dugulen ko labɛn !",
        error_minLength: "⚠️ A ka dugulen ko bɛ taa kelen ni saba !",
        error_maxLength: "⚠️ A ka dugulen ko ka taa bɛ taa talan ni tɔɔrɔ !",
        error_invalidChars: "⚠️ A ka dugulen ko kɛ bɛ yeɲin, baara, ni bɔ-joona bɛɛ kɛ !",
        creating_db_message: "Bambara : Création de votre base de données en cours...",
        loading_message: "Bambara : Veuillez patienter, chargement en cours...",
        loading_patient_message: "Bambara : Veuillez patienter un instant, s'il vous plaît...",
        created_db_message: "Bambara : Finalisation de la création de votre base de données...",
        color_text: "Kulɛriw",
        theme_text: "Tɛmu",
        add_new_text: "Farali",
        filter_text: "Wolomali",
        recherche_text: "ɲininin teliman...",
        calsse_text: "Kilasiw",
        refresh_text: "Kurayali",
        all_text: "Bɛɛ",
        lang_name_text: "Kan",
        calculator_text: "Jatekɛla",
        calendar_text: "Donfilɛla",
        error_calculate_text: "Filikɛra",
        profile_text: "Filikɛra",
        fullname_text: "Filikɛra",
        firstname_text: "Filikɛra",
        lastname_text: "Filikɛra",
        surname_text: "Filikɛra",
        sexe_text: "Filikɛra",
        birth_text: "Filikɛra",
        father_text: "Filikɛra",
        mother_text: "Filikɛra",
        contact_text: "Filikɛra",
        added_time_text: "Filikɛra",
        updated_time_text: "Filikɛra",
        status_text: "Filikɛra",
        actif_text: "Filikɛra",
        classe_text: "Filikɛra",
        option_text: "Filikɛra",
        update_student_text: "Filikɛra",
        see_detail_student_text: "Filikɛra",
        deactive_student_text: "Filikɛra",
        active_student_text: "Filikɛra",
        delete_student_text: "Filikɛra",
        filter_by_classe_text: "Filikɛra",
        filter_A_to_Z_text: "Filikɛra",
        filter_date_insc_text: "Filikɛra",
        students_number_text: "Kalandenw bɛɛ la jɛlen hakɛ",
        classe_number_text: "Kalansodenw bɛɛ la jɛlen hakɛ",
    },
    Français: {
        welcome_text: "Gérez votre établissement sans aucune compétence en informatique !",
        create_db_text: "CRÉER UNE BASE DE DONNÉES",
        create_btn_text: "CRÉER",
        create_btn_text_2: "CRÉER MAINTENANT",
        select_color_text: "Choisir une couleur",
        create_input_info_text: "Nom de votre établissement",
        error_empty: "⛔ Le nom de la base de données est requis.",
        error_minLength: "⚠️ Le nom doit contenir au moins 3 caractères.",
        error_maxLength: "⚠️ Le nom ne peut pas dépasser 30 caractères.",
        error_invalidChars: "⚠️ Le nom ne doit contenir que des lettres, chiffres, tirets ou underscores.",
        creating_db_message: "Création de votre base de données en cours...",
        loading_message: "Veuillez patienter, chargement en cours...",
        loading_patient_message: "Veuillez patienter un instant, s'il vous plaît...",
        created_db_message: "Finalisation de la création de votre base de données...",
        color_text: "Couleurs",
        theme_text: "Thème",
        add_new_text: "Ajout",
        filter_text: "Filtre",
        recherche_text: "Recherche en direct...",
        calsse_text: "Classes",
        refresh_text: "Rafraîchir",
        all_text: "Toutes",
        lang_name_text: "Langue",
        calculator_text: "Calculatrice",
        calendar_text: "Calendrier",
        error_calculate_text: "Erreur",
        profile_text: "Profil",
        fullname_text: "Nom Complet",
        firstname_text: "Prénom",
        lastname_text: "Nom",
        surname_text: "Surnom",
        sexe_text: "Sexe",
        birth_text: "Date de Nais",
        father_text: "Père",
        mother_text: "Mère",
        contact_text: "Contact",
        added_time_text: "Date d'ajout",
        updated_time_text: "Date de modifi",
        status_text: "Status",
        actif_text: "Actif",
        classe_text: "Classe",
        option_text: "Option",
        update_student_text: "Modifier",
        see_detail_student_text: "Voir plus",
        deactive_student_text: "Désactiver",
        active_student_text: "Activer",
        delete_student_text: "Supprimer",
        filter_by_classe_text: "Par classe",
        filter_A_to_Z_text: "De A à Z",
        filter_date_insc_text: "Par date d'inscription",
        students_number_text: "Le nombre total des élèves",
        classe_number_text: "Le nombre total des classes",
    },
    Anglais: {
        welcome_text: "Manage your institution with no IT skills required!",
        create_db_text: "CREATE A DATABASE",
        create_btn_text: "CREATE",
        create_btn_text_2: "CREATE NOW",
        select_color_text: "Choose a color",
        create_input_info_text: "Name of your institution",
        error_empty: "⛔ Database name is required.",
        error_minLength: "⚠️ The name must be at least 3 characters long.",
        error_maxLength: "⚠️ The name cannot exceed 30 characters.",
        error_invalidChars: "⚠️ The name must only contain letters, numbers, hyphens, or underscores.",
        creating_db_message: "Creating your database...",
        loading_message: "Please wait, loading in progress...",
        loading_patient_message: "Please wait a moment, please...",
        created_db_message: "Finalizing the creation of your database...",
        color_text: "Colors",
        theme_text: "Theme",
        add_new_text: "Add",
        filter_text: "Filter",
        recherche_text: "Live search...",
        calsse_text: "Classes",
        refresh_text: "Refresh",
        all_text: "All",
        lang_name_text: "Language",
        calculator_text: "Calculator",
        calendar_text: "Agenda",
        error_calculate_text: "Error",
        profile_text: "Profile",
        fullname_text: "Full Name",
        firstname_text: "First Name",
        lastname_text: "Last Name",
        surname_text: "Surname",
        sexe_text: "Sex",
        birth_text: "Birth Date",
        father_text: "Father",
        mother_text: "Mother",
        contact_text: "Contact",
        added_time_text: "Added At",
        updated_time_text: "Updated At",
        status_text: "Status",
        actif_text: "Actif",
        classe_text: "Classe",
        option_text: "Option",
        update_student_text: "Update",
        see_detail_student_text: "See more",
        deactive_student_text: "Deactive",
        active_student_text: "Active",
        delete_student_text: "Delete",
        filter_by_classe_text: "By classe",
        filter_A_to_Z_text: "From A to Z",
        filter_date_insc_text: "By registration date",
        students_number_text: "Total number of students",
        classe_number_text: "Total number of classes",
    },
};

export { Translator };
